name: efk-ccdp
apiVersion: 0.0.1
kind: ksonnet.io/parts
description: >
  EFK (elasticsearch-fluentd-kibana) is a common logging stack used with
  kubernetes. This is a modified version of the original prototype at ksonnet
author: Ulf Mansson <ulf.mansson@volvocars.com>
contributors:
- name: Tehut Getahun
  email: tehut@heptio.com
- name: Tamiko Terada
  email: tamiko@heptio.com
- name: Ulf Mansson
  email: ulf.mansson@volvocars.com
repository:
  type: file
  url: teams/devops/projects/ks-ccdp/efk-ccdp
keywords:
- elasticsearch
- fluentd
- kibana
- logging
- ccdp
quickStart:
  prototype: com.volvocars.ccdp.pkg.elasticsearch-kibana
  componentName: elasticsearch-kibana
  flags:
    name: elasticsearch-kibana
    namespace: default
    password: boots
  comment: Logging stack that processes input from fluentd.
license: Apache 2.0
